# Generated by Django 4.0 on 2022-06-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('tools', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
